### Get all notes
GET http://localhost:8080/notes

### Edit a note
PUT http://localhost:8080/notes/1
Content-Type: application/json

{
  "title": "Study",
  "content": "Revise coding"
}

### Create a note
POST http://localhost:8080/notes
Content-Type: application/json

{
  "title": "Study",
  "content": "Learn coding"
}