### Get all notes
GET http://localhost:8080/notes

### Edit a note
PUT http://localhost:8080/notes/252
Content-Type: application/json

{
  "title": "",
  "content": "Lift weights"
}

### Delete a note
DELETE http://localhost:8080/notes/152
Content-Type: application/json

### Create a note
POST http://localhost:8080/notes
Content-Type: application/json

{
  "title": "Gym",
  "content": "Lift weights"
}